services:
  app:
    build:
      dockerfile: ./Dockerfile
    container_name: app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - backend

  webserver:
    image: nginx:alpine
    container_name: webserver
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    networks:
      - backend

  db:
    image: postgres:13-alpine
    container_name: db
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=honest_restaurant_api
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    volumes:
      - pgadmindata:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:

volumes:
  pgadmindata:
  dbdata:
